### ISSUE TITLE
Python3.12 compilation error: ‘PyGenObject’ has no member named ‘gi_code’

### ISSUE THREAD

**Issue by arkamar** [ICRAR/ijson#95]
**Describe the bug**

ijson-3.2.0 fails to compile with Python3.12 with following error message:
```
 * python3_12: running distutils-r1_run_phase distutils-r1_python_compile
python3.12 setup.py build_ext -j 8
running build_ext
building 'ijson.backends._yajl2' extension
creating build
creating build/temp.linux-x86_64-cpython-312
creating build/temp.linux-x86_64-cpython-312/ijson
creating build/temp.linux-x86_64-cpython-312/ijson/backends
creating build/temp.linux-x86_64-cpython-312/ijson/backends/yajl2_c
x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -pipe -DNDEBUG -fPIC -Iijson/backends/yajl2_c -I/usr/include/python3.12 -c ijson/backends/yajl2_c/async_reading_generator.c -o build/temp.linux-x86_64-cpython-312/ijs
on/backends/yajl2_c/async_reading_generator.o
ijson/backends/yajl2_c/async_reading_generator.c: In function ‘is_gen_coroutine’:
ijson/backends/yajl2_c/async_reading_generator.c:80:72: error: ‘PyGenObject’ has no member named ‘gi_code’
   80 |                 PyCodeObject *code = (PyCodeObject *)((PyGenObject*) o)->gi_code;
      |                                                                        ^~
error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
```

**Execution information:**
 - Python version: 3.12
 - ijson version: 3.2.0
 - ijson installation method: package manager
 - OS Gentoo Linux `~amd64`

**Comment by rtobar** [comment]
Thanks @arkamar for reporting, will have a look and prepare ijson to be 3.12 ready.

**Comment by rtobar** [comment]
@arkamar please check the contents of the `issue-95` branch. The package still builds and all tests pass correctly in version <=3.11, and locally I tried in a 3.12 docker container with success; I'd still like to hear from you that all tests pass correctly, in particular all the `*AsyncTypesCoroutineTests` ones.

**Comment by arkamar** [comment]
Yes, `issue-95` works, it builds and all test pass in Python3.{10..12} and pypy3 as well.

Btw, you have typo in headline of commit message https://github.com/ICRAR/ijson/commit/80caf898d79cb7deb0611bb4dfed38dfe0725cec: 3.11 -> 3.12

**Comment by rtobar** [comment]
Ahhhh thanks for testing and reporting the typo, I'll redo that commit and merge to `master`, then close this as solved.

**Comment by rtobar** [comment]
Fix merged to `master`, thanks again for reporting.
